name: Ngrok_Windows_Github_RDP (Sounds On)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
      - name: Downloading Essentials
        run: |
          Invoke-WebRequest -Uri https://gitlab.com/chamod12/ngrok-win10-rdp/-/raw/main/Downloads.bat -OutFile Downloads.bat
          cmd /c Downloads.bat

      - name: Connecting Ngrok Account
        run: ngrok config add-authtoken $Env:2kCtEQF7flPQ4Yz0GTpLcmjAeuR_2VnoiNU4EDtbUKbj7qSxW
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.2kCtEQF7flPQ4Yz0GTpLcmjAeuR_2VnoiNU4EDtbUKbj7qSxW }}
          
      - name: Enabling RDP Access
        run: cmd /c Acess.bat       

      - name: Log In To Remote Desktop Protocol
        run: cmd /c startaudio.bat

      - name: Time Count
        run: cmd /c loop.bat
